name: messageapp
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_bloc:
  shared_preferences:
  firebase_auth:
  cloud_firestore:
  google_sign_in:
  flutter_facebook_login:
  firebase_storage:
  image_picker:
  cached_network_image:
  fluttertoast:
  intl:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  fonts:
    - family: PoiretOne
      fonts:
        - asset: fonts/PoiretOne-Regular.ttf